FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        libgstreamer1.0-dev:arm64 \
        libgstreamer-plugins-base1.0-dev:arm64 \
        libglib2.0-dev:arm64 \
        libgstrtspserver-1.0-dev:arm64 \
    && rm -rf /var/lib/apt/lists/*
